{% set name = "pyreadstat" %}
{% set version = "1.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7fb6a1ee42aeea7068ec1cefaa3f5e18c49ea400c5d082e59e216b5575cc66e1

build:
  number: 0
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler("m2w64_c") }}  # [win]
    - {{ compiler('c') }}  # [not win]
  host:
    - python
    - pip
    - cython
    - m2w64-toolchain  # [win]
    - libpython  # [win]
    - zlib  # [not win]
  run:
    - python
    - pandas
    - m2w64-gcc-libs  # [win]
    - zlib  # [not win]

test:
  imports:
    - pyreadstat

about:
  home: https://github.com/Roche/pyreadstat
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: read SAS, SPSS and STATA files into pandas data frames
  description: |
    A Python package to read SAS (sas7bdat, sas7bcat, xport/xpt), SPSS (sav, zsav, por) and Stata (dta) files into pandas data frames. It is a wrapper around the C library readstat.
  doc_url: https://github.com/Roche/pyreadstat
  dev_url: https://github.com/Roche/pyreadstat

extra:
  recipe-maintainers:
    - ofajardo
