{% set name = "pyreadstat" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f06ace3dbdde1810f16c579e66e1acf236eec421c785c0df55686ffd9ee3d897

build:
  number: 1
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}  # [win]
    - {{ compiler('c') }}  # [not win]
  host:
    - python
    - pip
    - cython
    - zlib  # [not win]
    - zlib  # [win]
    - libiconv  # [win]
  run:
    - python
    - pandas
    - zlib  # [not win]
    - zlib  # [win]
    - libiconv  # [win]

test:
  imports:
    - pyreadstat

about:
  home: https://github.com/Roche/pyreadstat
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: read SAS, SPSS and STATA files into pandas data frames
  description: |
    A Python package to read SAS (sas7bdat, sas7bcat, xport/xpt), SPSS (sav, zsav, por) and Stata (dta) files into pandas data frames. It is a wrapper around the C library readstat.
  doc_url: https://github.com/Roche/pyreadstat
  dev_url: https://github.com/Roche/pyreadstat

extra:
  recipe-maintainers:
    - ofajardo
