{% set name = "pyreadstat" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4ebb105119e4d4026328cd611e5e582e7456d14057be25070d5ebf7ff730ed78

build:
  number: 0
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - setuptools
    - wheel
    - cython 
    - zlib 
    - libiconv >=1.16  # [win]
  run:
    - python
    - narwhals >=2.10.1
    - pandas >=1.2.0
    - numpy
    - zlib
    - libiconv  # [win]

test:
  imports:
    - pyreadstat
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Roche/pyreadstat
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: read SAS, SPSS and STATA files into pandas data frames
  description: |
    A Python package to read SAS (sas7bdat, sas7bcat, xport/xpt),
    SPSS (sav, zsav, por) and Stata (dta) files into pandas data frames.
    It is a wrapper around the C library readstat.
  doc_url: https://github.com/Roche/pyreadstat/blob/master/README.md
  dev_url: https://github.com/Roche/pyreadstat

extra:
  recipe-maintainers:
    - ofajardo
  anaconda-services:
    recipe-maintainers:
       - bkreider
    comment: "https://anaconda.zendesk.com/agent/tickets/72455"

