{% set name = "pyreadstat" %}
{% set version = "1.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Roche/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 987c102576af2cfc8656b81098eb52d1abf931953634985f16e0ed2032d8aa96

build:
  number: 0
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  patches:                            # [win]
    - skip-broken-test-windows.patch  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython
    - zlib 1.2.13
    - libiconv  # [win]
  run:
    - python
    - pandas
    - zlib
    - libiconv  # [win]

test:
  source_files:
    - tests
    - test_data
  imports:
    - pyreadstat
  requires:
    - pip
  commands:
    - pip check
    - python tests/test_basic.py  # [not win]
    - python tests/test_basic.py  # [win]

about:
  home: https://github.com/Roche/pyreadstat
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: read SAS, SPSS and STATA files into pandas data frames
  description: |
    A Python package to read SAS (sas7bdat, sas7bcat, xport/xpt),
    SPSS (sav, zsav, por) and Stata (dta) files into pandas data frames.
    It is a wrapper around the C library readstat.
  doc_url: https://github.com/Roche/pyreadstat/blob/master/README.md
  dev_url: https://github.com/Roche/pyreadstat

extra:
  recipe-maintainers:
    - ofajardo
