{% set name = "pyreadstat" %}
{% set version = "1.3.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Roche/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: dacf76cfa871d63d4b4de5011447b8bbda8430498cb463093fd5400529e7e8a3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    - wheel
    - cython 3.2.5
    - zlib {{ zlib }}
    - libiconv {{ libiconv }}  # [win]
    - narwhals >=2.10.1
    - numpy {{ numpy }}
  run:
    - python
    - pandas >=1.2.0
    - zlib
    - libiconv  # [win]
    - narwhals >=2.10.1

test:
  source_files:
    - tests
    - test_data
  files:
    # Moving "import pyreadstat" to support testing as a module.
    - fix-test-imports.patch
  imports:
    - pyreadstat
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - patch -Np1 -i fix-test-imports.patch --binary
    # Skipping expected failing test on Windows.
    - pytest tests/test_basic.py -k "not test_sas7bdat_international"  # [win]
    - pytest tests/test_basic.py  # [not win]

about:
  home: https://github.com/Roche/pyreadstat
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: read SAS, SPSS and STATA files into pandas data frames
  description: |
    A Python package to read SAS (sas7bdat, sas7bcat, xport/xpt),
    SPSS (sav, zsav, por) and Stata (dta) files into pandas data frames.
    It is a wrapper around the C library readstat.
  doc_url: https://github.com/Roche/pyreadstat/blob/master/README.md
  dev_url: https://github.com/Roche/pyreadstat

extra:
  recipe-maintainers:
    - ofajardo
