travis:
  secure:
    BINSTAR_TOKEN: q9P+hw8WyRvpgP3GKDdyU1kA/d/jgEbw84CMlOJ/NNfTnsMmtad5jgxLOn3v5Qwr+9NH4gBvgilEV/g55/jcI7KN3NWhATmiO41aBNuPmHds08bV/yj/0EuYjP9V9B7pPEnASqrjsaHkPe9esKS3H95x9wbOTC3Xx6ij6sI8KBwsAnHsWUJ7bQVYPJWZsUR4gPDU8fzpDjBMwb3ApFvsTfgSsTFkQjXKCrBwZzxTMl2YAxi82PFptXgXVnD10iwoyAtT0rXSENIz7iebA2eE2Oh92ngs1qr+tcId1YDq2I50NUqVj8CbvqEdd+K9eddHh17CJ5Y4Kn46IpRqn0ixy1M7xuAi7G1g6iQbux8oRI7RypbPRMt0Wc0oXD8+Xty2vj1Ime3ZFBOR3FLsdcx2CR8sM3tefpNgAZyqTNp4bYNyRKz7fprgA3HGqX4x05JID+kH1F3pPIlkDukerxuPkC4jhO7k6E3eSp+c57b3OMG8qAju1qs+tWf5+mbK6hDl+A3ZyXrIyX1NNwVqJEXgpIhULcMQ1znKVBCiEAwKnCOKAQQthOTmyrFhQQGgTzwAr32DWuot1veMZJcxHm488h7sRmoENgfDY7koMlIGKmNghvL7jK7DjBZ5su1kcQ8mYX3zuLg0szpP11rfeI5bExbKT5zQRL6AJQbnWAHVEN0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
